### ISSUE TITLE
Maths / Calculator: Backspace keypress does not do anything

### ISSUE THREAD

**Issue by divyeshbirawat** [prozilla-os/ProzillaOS#10]
In Maths / calculator component, on pressing backspace key, there was no action being performed.

**To Reproduce**
1. Go to Maths App
2. Type any number
3. Press backspace key

**Expected behavior**
Expected behavior is that the last input should be removed / deleted

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 126.0.6478.127

**Comment by Prozilla** [comment]
Fixed in: 618c2fe

Congratulations!
