### ISSUE TITLE
Single HTML file.

### ISSUE THREAD

**Issue by MuhammedSaleem-Brej** [prozilla-os/ProzillaOS#11]
Hello, I hope you will provide a copy of this operating system as a single HTML file that can be easily shared among users and run anywhere, even on smart devices, without the need for complex tools such as NodeJS and the use of a terminal. Thank you very much.

**Comment by Prozilla** [comment]
Something like this: https://github.com/prozilla-os/ProzillaOS/blob/gh-pages/index.html ?

**Comment by MuhammedSaleem-Brej** [comment]
Yes, that is what I mean, but I would like to provide a pre-built version that the user can download and run easily without having to build from source if the application does not rely on the web server primarily, for example, to store user data. Even I, as a web developer, faced difficulty in building the application and it did not work for me.  The build required some dependencies, and when I installed it, some errors appeared.

**Comment by Prozilla** [comment]
> if the application does not rely on the web server primarily, for example, to store user data.

Could you elaborate on this please? Do you want the application to work without having to store user data or are you asking for an offline storage solution?

> The build required some dependencies, and when I installed it, some errors appeared.

Could you show me the errors that appeared in a new issue so I can work on solving them?

**Comment by MuhammedSaleem-Brej** [comment]
"if the application does not rely on the web server primarily, for example, to store user data."
In the above-mentioned part of the message, I was wondering whether the application could be run independently on a web browser without the need for a web server, or is it designed to be in two parts, a front end and a back end?

**Comment by Prozilla** [comment]
This application is purely frontend, but as far as I know, you still need a web server to serve the necessary files, either locally on your PC or online via a web service. I'm wondering why you would want to avoid using a web server when running this website, could you describe your goal?

**Comment by MuhammedSaleem-Brej** [comment]
There are many reasons that push me to avoid using a web server with this application. The first reason is ease. If this application was a single independent HTML file, it would be much easier for users to download and run it with the click of a button without the need for additional steps such as setting up the web server and it would be completely cross-platform.  It is more flexible, as it will work on any device that has a web browser, and it will be easier to share and transfer. The second reason is speed, as the application’s connection with the web server may consume more time. The third reason is security, as the application’s connection with the web server may be exposed to hacking, which leads to receiving fake files.  The fourth reason is the need for an Internet connection. When a user uses the cloud services that host this application, he will need an Internet connection, and this is not always available.

**Comment by Prozilla** [comment]
Do you have any other real-world examples of websites that provide a download as a single HTML file? This is my first time hearing about this approach. Wouldn't this also be possible in the form of a PWA? Besides, most of your arguments, including being easy to share with friends, also apply to the current form, a website, which can easily be shared just by sending a URL. Sorry if I sound ignorant but it sounds like a lot of work for not so many benefits.

**Comment by MuhammedSaleem-Brej** [comment]
There is already a project called LumiOS that allows downloading it as a standalone HTML file. However, the problem with that project is that it's closed-source. As for the popularity of bundling web project files, tools have recently emerged called Web Bundlers. The function of these tools is to bundle web project files into unified files. For example, bundling all scripts into a single script or something similar, and the bundling process can be customized as desired. In the end, I’m not demanding that all websites take this step, but this particular idea should be considered because operating systems, as we know, are distributed as a single file in ISO or IMG format. Finally, I apologize, I know I may have given you a headache, but this is not something I'm directing at you—it's just a suggestion you can accept or reject, and I would be happy either way. Thank you very much for your patience.

**Comment by Prozilla** [comment]
> Even I, as a web developer, faced difficulty in building the application and it did not work for me. The build required some dependencies, and when I installed it, some errors appeared.

Could you create a new issue and write the steps to reproduce this bug, @MuhammedSaleem-Brej ?

**Comment by MuhammedSaleem-Brej** [comment]
Alright, I will give it another try. This will require me to re-download the necessary libraries. But before I do that, and to be fair and not misjudge the application, the folder I tried to build from is the DIST folder. Is this the correct folder to start from? Just a note, I’m not very skilled in dealing with Node.js packages.

**Comment by Prozilla** [comment]
This thread is going slightly off-topic, but the folder you need to build depends on which part of the project you are trying to run. If you want to build the website, make sure you have pnpm installed and run `pnpm run demo:build`. For more information about the different scripts, check out the readme file.
