### ISSUE TITLE
Spotify App

### ISSUE THREAD

**Issue by Prozilla** [prozilla-os/ProzillaOS#17]

**Comment by taynotfound** [comment]
@Prozilla Spotify itself probs won't be doable, what could work is maybe a Media Player that interacts with a VPS running a Song Distributor (VSD for Short) that supplies the Web App with a MP3 and the OS has a player for it

**Comment by taynotfound** [comment]
If you want, assign me to the Idea and I will take a closer deep dive

**Comment by Prozilla** [comment]
Alright, sounds good!
